services:
  neo4j:
    image: neo4j:5
    container_name: ecosystem-neo4j
    environment:
      NEO4J_AUTH: neo4j/test1234
    volumes:
      - neo4j_data:/data
    networks:
      - ecosystem_net

  backend:
    build: ./ecosystem_analyzer
    container_name: ecosystem-backend
    depends_on:
      - neo4j
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: test1234
    networks:
      - ecosystem_net

  frontend:
    build: ./UI
    container_name: ecosystem-frontend
    depends_on:
      - backend
    ports:
      - "8501:8501"
    networks:
      - ecosystem_net

volumes:
  neo4j_data:

networks:
  ecosystem_net:
    driver: bridge